import * as React from "react";
import {
  Edit,
  SimpleForm,
  EditProps,
  TextInput,
  NumberInput,
  SelectInput,
} from "react-admin";

export const InvestorEdit = (props: EditProps): React.ReactElement => {
  return (
    <Edit {...props}>
      <SimpleForm>
        <TextInput
          label="AboutDescriptionOfFirm"
          multiline
          source="aboutDescriptionOfFirm"
        />
        <NumberInput
          label="AssetsAllocatedToAlternativesEuros"
          source="assetsAllocatedToAlternativesEuros"
        />
        <NumberInput
          label="AssetsAllocatedToAlternativesLocalCurrency"
          source="assetsAllocatedToAlternativesLocalCurrency"
        />
        <NumberInput
          label="AssetsAllocatedToAlternativesPercentage"
          source="assetsAllocatedToAlternativesPercentage"
        />
        <NumberInput
          label="AssetsAllocatedToAlternativesUSDollars"
          source="assetsAllocatedToAlternativesUsDollars"
        />
        <NumberInput
          label="AssetsAllocatedToCashEuros"
          source="assetsAllocatedToCashEuros"
        />
        <NumberInput
          label="AssetsAllocatedToCashLocalCurrency"
          source="assetsAllocatedToCashLocalCurrency"
        />
        <NumberInput
          label="AssetsAllocatedToCashPercentage"
          source="assetsAllocatedToCashPercentage"
        />
        <NumberInput
          label="AssetsAllocatedToCashUSDollars"
          source="assetsAllocatedToCashUsDollars"
        />
        <NumberInput
          label="AssetsAllocatedToEquitiesEuros"
          source="assetsAllocatedToEquitiesEuros"
        />
        <NumberInput
          label="AssetsAllocatedToEquitiesLocalCurrency"
          source="assetsAllocatedToEquitiesLocalCurrency"
        />
        <NumberInput
          label="AssetsAllocatedToEquitiesPercentage"
          source="assetsAllocatedToEquitiesPercentage"
        />
        <NumberInput
          label="AssetsAllocatedToEquitiesUSDollars"
          source="assetsAllocatedToEquitiesUsDollars"
        />
        <NumberInput
          label="AssetsAllocatedToFixedIncomeEuros"
          source="assetsAllocatedToFixedIncomeEuros"
        />
        <NumberInput
          label="AssetsAllocatedToFixedIncomeLocalCurrency"
          source="assetsAllocatedToFixedIncomeLocalCurrency"
        />
        <NumberInput
          label="AssetsAllocatedToFixedIncomePercentage"
          source="assetsAllocatedToFixedIncomePercentage"
        />
        <NumberInput
          label="AssetsAllocatedToFixedIncomeUSDollars"
          source="assetsAllocatedToFixedIncomeUsDollars"
        />
        <NumberInput
          label="AssetsAllocatedToOtherEuros"
          source="assetsAllocatedToOtherEuros"
        />
        <NumberInput
          label="AssetsAllocatedToOtherLocalCurrency"
          source="assetsAllocatedToOtherLocalCurrency"
        />
        <NumberInput
          label="AssetsAllocatedToOtherPercentage"
          source="assetsAllocatedToOtherPercentage"
        />
        <NumberInput
          label="AssetsAllocatedToOtherUSDollars"
          source="assetsAllocatedToOtherUsDollars"
        />
        <NumberInput
          label="AssetsUnderManagementInEuros"
          source="assetsUnderManagementInEuros"
        />
        <NumberInput
          label="AssetsUnderManagementInInvestorCurrency"
          source="assetsUnderManagementInInvestorCurrency"
        />
        <NumberInput
          label="AssetsUnderManagementInUSDollars"
          source="assetsUnderManagementInUsDollars"
        />
        <TextInput label="CityFirmsMainOffice" source="cityFirmsMainOffice" />
        <TextInput label="contactNumber" source="contactNumber" />
        <TextInput label="country" source="country" />
        <TextInput
          label="CountryFirmsMainOffice"
          source="countryFirmsMainOffice"
        />
        <TextInput
          label="CurrencyFirmInvestsIn"
          source="currencyFirmInvestsIn"
        />
        <TextInput label="email" source="email" type="email" />
        <TextInput
          label="EmailAddressOfFirm"
          source="emailAddressOfFirm"
          type="email"
        />
        <TextInput label="FaxNumberOfFirm" source="faxNumberOfFirm" />
        <TextInput
          label="FirmsGeneralInvestmentConsultant"
          source="firmsGeneralInvestmentConsultant"
        />
        <TextInput
          label="LocalLanguageNameOfFirm"
          source="localLanguageNameOfFirm"
        />
        <NumberInput
          label="MaximumTargetAllocationToAlternativesEuros"
          source="maximumTargetAllocationToAlternativesEuros"
        />
        <NumberInput
          label="MaximumTargetAllocationToAlternativesLocalCurrency"
          source="maximumTargetAllocationToAlternativesLocalCurrency"
        />
        <NumberInput
          label="MaximumTargetAllocationToAlternativesPercentage"
          source="maximumTargetAllocationToAlternativesPercentage"
        />
        <NumberInput
          label="MaximumTargetAllocationToAlternativesUSDollars"
          source="maximumTargetAllocationToAlternativesUsDollars"
        />
        <NumberInput
          label="MaximumTargetAllocationToCashEuros"
          source="maximumTargetAllocationToCashEuros"
        />
        <NumberInput
          label="MaximumTargetAllocationToCashLocalCurrency"
          source="maximumTargetAllocationToCashLocalCurrency"
        />
        <NumberInput
          label="MaximumTargetAllocationToCashPercentage"
          source="maximumTargetAllocationToCashPercentage"
        />
        <NumberInput
          label="MaximumTargetAllocationToCashUSDollars"
          source="maximumTargetAllocationToCashUsDollars"
        />
        <NumberInput
          label="MaximumTargetAllocationToEquitiesEuros"
          source="maximumTargetAllocationToEquitiesEuros"
        />
        <NumberInput
          label="MaximumTargetAllocationToEquitiesLocalCurrency"
          source="maximumTargetAllocationToEquitiesLocalCurrency"
        />
        <NumberInput
          label="MaximumTargetAllocationToEquitiesPercentage"
          source="maximumTargetAllocationToEquitiesPercentage"
        />
        <NumberInput
          label="MaximumTargetAllocationToEquitiesUSDollars"
          source="maximumTargetAllocationToEquitiesUsDollars"
        />
        <NumberInput
          label="MaximumTargetAllocationToFixedIncomeEuros"
          source="maximumTargetAllocationToFixedIncomeEuros"
        />
        <NumberInput
          label="MaximumTargetAllocationToFixedIncomeLocalCurrency"
          source="maximumTargetAllocationToFixedIncomeLocalCurrency"
        />
        <NumberInput
          label="MaximumTargetAllocationToFixedIncomePercentage"
          source="maximumTargetAllocationToFixedIncomePercentage"
        />
        <NumberInput
          label="MaximumTargetAllocationToFixedIncomeUSDollars"
          source="maximumTargetAllocationToFixedIncomeUsDollars"
        />
        <NumberInput
          label="MaximumTargetAllocationToOtherEuros"
          source="maximumTargetAllocationToOtherEuros"
        />
        <NumberInput
          label="MaximumTargetAllocationToOtherLocalCurrency"
          source="maximumTargetAllocationToOtherLocalCurrency"
        />
        <NumberInput
          label="MaximumTargetAllocationToOtherPercentage"
          source="maximumTargetAllocationToOtherPercentage"
        />
        <NumberInput
          label="MaximumTargetAllocationToOtherUSDollars"
          source="maximumTargetAllocationToOtherUsDollars"
        />
        <NumberInput
          label="MinimumTargetAllocationToAlternativesEuros"
          source="minimumTargetAllocationToAlternativesEuros"
        />
        <NumberInput
          label="MinimumTargetAllocationToAlternativesLocalCurrency"
          source="minimumTargetAllocationToAlternativesLocalCurrency"
        />
        <NumberInput
          label="MinimumTargetAllocationToAlternativesPercentage"
          source="minimumTargetAllocationToAlternativesPercentage"
        />
        <NumberInput
          label="MinimumTargetAllocationToAlternativesUSDollars"
          source="minimumTargetAllocationToAlternativesUsDollars"
        />
        <NumberInput
          label="MinimumTargetAllocationToCashEuros"
          source="minimumTargetAllocationToCashEuros"
        />
        <NumberInput
          label="MinimumTargetAllocationToCashLocalCurrency"
          source="minimumTargetAllocationToCashLocalCurrency"
        />
        <NumberInput
          label="MinimumTargetAllocationToCashPercentage"
          source="minimumTargetAllocationToCashPercentage"
        />
        <NumberInput
          label="MinimumTargetAllocationToCashUSDollars"
          source="minimumTargetAllocationToCashUsDollars"
        />
        <NumberInput
          label="MinimumTargetAllocationToEquitiesEuros"
          source="minimumTargetAllocationToEquitiesEuros"
        />
        <NumberInput
          label="MinimumTargetAllocationToEquitiesLocalCurrency"
          source="minimumTargetAllocationToEquitiesLocalCurrency"
        />
        <NumberInput
          label="MinimumTargetAllocationToEquitiesPercentage"
          source="minimumTargetAllocationToEquitiesPercentage"
        />
        <NumberInput
          label="MinimumTargetAllocationToEquitiesUSDollars"
          source="minimumTargetAllocationToEquitiesUsDollars"
        />
        <NumberInput
          label="MinimumTargetAllocationToFixedIncomeEuros"
          source="minimumTargetAllocationToFixedIncomeEuros"
        />
        <NumberInput
          label="MinimumTargetAllocationToFixedIncomeLocalCurrency"
          source="minimumTargetAllocationToFixedIncomeLocalCurrency"
        />
        <NumberInput
          label="MinimumTargetAllocationToFixedIncomePercentage"
          source="minimumTargetAllocationToFixedIncomePercentage"
        />
        <NumberInput
          label="MinimumTargetAllocationToFixedIncomeUSDollars"
          source="minimumTargetAllocationToFixedIncomeUsDollars"
        />
        <NumberInput
          label="MinimumTargetAllocationToOtherEuros"
          source="minimumTargetAllocationToOtherEuros"
        />
        <NumberInput
          label="MinimumTargetAllocationToOtherLocalCurrency"
          source="minimumTargetAllocationToOtherLocalCurrency"
        />
        <NumberInput
          label="MinimumTargetAllocationToOtherPercentage"
          source="minimumTargetAllocationToOtherPercentage"
        />
        <NumberInput
          label="MinimumTargetAllocationToOtherUSDollars"
          source="minimumTargetAllocationToOtherUsDollars"
        />
        <TextInput label="name" source="name" />
        <TextInput label="NameOfFirm" source="nameOfFirm" />
        <NumberInput
          step={1}
          label="NumberOfKnownInvestmentsMade"
          source="numberOfKnownInvestmentsMade"
        />
        <TextInput
          label="RegionFirmsMainOffice"
          source="regionFirmsMainOffice"
        />
        <TextInput
          label="SecondaryOfficeLocationsOfFirm"
          multiline
          source="secondaryOfficeLocationsOfFirm"
        />
        <TextInput
          label="StateOrCountyOfFirmsMainOffice"
          source="stateOrCountyOfFirmsMainOffice"
        />
        <TextInput label="StreetAddressOfFirm" source="streetAddressOfFirm" />
        <TextInput
          label="TelephoneNumberOfFirm"
          source="telephoneNumberOfFirm"
        />
        <SelectInput
          source="typeOfFirm"
          label="TypeOfFirm"
          choices={[{ label: "Option 1", value: "Option1" }]}
          optionText="label"
          allowEmpty
          optionValue="value"
        />
        <TextInput label="UniqueFirmIdentifier" source="uniqueFirmIdentifier" />
        <TextInput label="WebsiteOfFirm" source="websiteOfFirm" />
        <NumberInput
          step={1}
          label="YearFirmWasEstablished"
          source="yearFirmWasEstablished"
        />
        <TextInput
          label="ZipCodeOfFirmsMainOffice"
          source="zipCodeOfFirmsMainOffice"
        />
      </SimpleForm>
    </Edit>
  );
};
