/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FundService } from "../fund.service";
import { FundCreateInput } from "./FundCreateInput";
import { Fund } from "./Fund";
import { FundFindManyArgs } from "./FundFindManyArgs";
import { FundWhereUniqueInput } from "./FundWhereUniqueInput";
import { FundUpdateInput } from "./FundUpdateInput";

export class FundControllerBase {
  constructor(protected readonly service: FundService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Fund })
  async createFund(@common.Body() data: FundCreateInput): Promise<Fund> {
    return await this.service.createFund({
      data: data,
      select: {
        createdAt: true,
        currency: true,
        id: true,
        investmentStrategy: true,
        name: true,
        size: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Fund] })
  @ApiNestedQuery(FundFindManyArgs)
  async funds(@common.Req() request: Request): Promise<Fund[]> {
    const args = plainToClass(FundFindManyArgs, request.query);
    return this.service.funds({
      ...args,
      select: {
        createdAt: true,
        currency: true,
        id: true,
        investmentStrategy: true,
        name: true,
        size: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Fund })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async fund(
    @common.Param() params: FundWhereUniqueInput
  ): Promise<Fund | null> {
    const result = await this.service.fund({
      where: params,
      select: {
        createdAt: true,
        currency: true,
        id: true,
        investmentStrategy: true,
        name: true,
        size: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Fund })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFund(
    @common.Param() params: FundWhereUniqueInput,
    @common.Body() data: FundUpdateInput
  ): Promise<Fund | null> {
    try {
      return await this.service.updateFund({
        where: params,
        data: data,
        select: {
          createdAt: true,
          currency: true,
          id: true,
          investmentStrategy: true,
          name: true,
          size: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Fund })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFund(
    @common.Param() params: FundWhereUniqueInput
  ): Promise<Fund | null> {
    try {
      return await this.service.deleteFund({
        where: params,
        select: {
          createdAt: true,
          currency: true,
          id: true,
          investmentStrategy: true,
          name: true,
          size: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
